# Site settings
title: Ryan Amstutz
email: rgbamstutz@gmail.com
url: https://rgbamstutz.github.io
description: "Computer Science Graduate and Deep/Machine Learning Practitioner"
keywords: "Deep Learning Engineer, Machine Learning Engineer, Natural Language Processing, Computer Vision, Forecast Modeling, Game Developper"
skills: "TensorFlow Certified - Deep/Machine Learning Practitioner - Game Developper"
meta_author: Amstutz Ryan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 482980 #80B3FF
  primary-rgb: "72,41,128" #"128,179,255"
  secondary: 271646 #FD6E8A
  secondary-dark: 271646 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  social: Other Links
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ryan-amstutz/
  - title: github
    url: https://github.com/RGBAmstutz

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
